name: Code Check

on:
  pull_request:

jobs:
  core_biome_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: pnpm install

      - name: Run Setup
        run: pnpm @core lint

  core_tsc_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: pnpm install

      - name: Run Setup
        run: pnpm @core tsc

  notify:
    runs-on: ubuntu-latest
    needs: [core_biome_check, core_tsc_check]
    if: always()
    steps:
      - name: Send Slack notification on failure
        if: ${{ needs.core_biome_check.result == 'failure' || needs.core_tsc_check.result == 'failure' }}
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook: ${{ secrets.SLACK_WORKFLOW_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "GitHub Actions failed! ðŸš¨\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
